name: Build & Release hk4e-patch-universal

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 安装系统依赖
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev build-essential

      # 3️⃣ 安装 Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 4️⃣ 构建 Release
      - name: Build Release
        run: cargo build --release --verbose

      # 5️⃣ 运行测试
      - name: Run Tests
        run: cargo test --verbose

      # 6️⃣ 上传 artifact
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hk4e-patch-universal
          path: target/release/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 下载 artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hk4e-patch-universal
          path: release_files

      # 2️⃣ 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "hk4e-patch-universal v${{ github.run_number }}"
          body: "Automated release from GitHub Actions"

      # 3️⃣ 上传二进制到 Release
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: release_files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
