name: Rust Build & Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. 安装系统依赖
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev build-essential

    # 3. 安装 Rust
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy,rustfmt

    # 4. 编译 Release 版本
    - name: Build Release
      run: cargo build --release --verbose

    # 5. 运行测试
    - name: Run tests
      run: cargo test --verbose

    # 6. 上传 Release 编译产物
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hk4e-patch-universal
        path: target/release/
